name: ecommerce_advanced
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #animation
  animate_do: 
#localization
  flutter_localization: ^0.2.0
  cupertino_icons: ^1.0.2

  #core
  connectivity_plus: ^5.0.2
  flutter_dotenv: 
  flutter_screenutil: ^5.9.0
  flutter_native_splash: ^2.3.10
  get_it: ^7.6.7

  #firebase
  firebase_core: ^2.27.0
  #bloc
  flutter_bloc: ^8.1.4
  shared_preferences: ^2.2.2

  freezed_annotation: ^2.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/1024.png"
  adaptive_icon_background: "#0E0E0E"
  adaptive_icon_foreground: "assets/icons/play_store_512.png"

flutter:
  uses-material-design: true

  assets:
    - .env.dev
    - .env.prod
    - assets/images/core/
    - lang/ar.json
    - lang/en.json

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/arapic/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/arapic/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/arapic/cairo/Cairo-Bold.ttf
          weight: 700
    - family: Blinker
      fonts:
        - asset: assets/fonts/english/blinker/Blinker-Regular.ttf
          weight: 400
        - asset: assets/fonts/english/blinker/Blinker-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/english/blinker/Blinker-Bold.ttf
          weight: 700

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/common/style
  filename: app_images.dart
  field_prefix: